<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\db\ActiveRecord;

class Chat extends ActiveRecord
{
    public static function tableName()
    {
        return '{{chat}}'; //parent::tableName(); // TODO: Change the autogenerated stub
    }
}

class ChatForm extends Model
{
    public $message;
    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['message'], 'required'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    public function sendChatMessage($message)
    {
        $chat = new \app\models\Chat();
        $chat->userID = Yii::$app->user->id;
        $chat->message = Yii::$app->user->identity->username.': '.$message;
        $chat->save();
    }
    public function banMessage($msg_id)
    {
        $chat = Chat::findOne($msg_id);
        $chat->ban = 1;
        $chat->save();
    }
    public function unbanMessage($msg_id)
    {
        $chat = Chat::findOne($msg_id);
        $chat->ban = '';
        $chat->save();
    }
}
